# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Install missing ws module and its type declarations
RUN npm install ws @types/ws

# Copy source code to work directory
COPY . .

# Build the TypeScript code
RUN npm run build

# Start the server
CMD ["npm", "start"]
